### PR TITLE
feat(sam): Parameters SAM template section (#62)

### PR DESCRIPTION
**Pull request by OlgaKaz**
This change is [Reviewable](https://reviewable.io/reviews/petelind/mercury/67)

### CODE REVIEW

**Comment by petelind** [comment]
All things are in place, but I suggest you use 'formal strings' when do template - keys are not required, but values strongly suggested, like Type: 'String'

**Comment by petelind** [comment]
@OlgaKaz, any chance you'll fix it Wed morning? Shall be 3 mins

**Comment by OlgaKaz** [comment]
String values are fixed

**Comment by petelind** [comment]
Great, thank you!

**Pull request merged**
